### ISSUE TITLE
Change in 6.05 breaks tests in Catalyst

### ISSUE THREAD

**Issue by jjn1056** [libwww-perl/HTTP-Message#2]
Hi,

I'll offer a patch in a bit but I noticed this change: https://metacpan.org/diff/release/GAAS/HTTP-Message-6.04/GAAS/HTTP-Message-6.05#lib/HTTP/Headers.pm

gets me a lot of the following errors:

"Bareword "::std_case" not allowed while "strict subs" in use at (eval 751) line 28."

My guess is that the ::std_case is somehow being thought of as a method or something.  I don't know of a reason to not instead use __std_case if you want something private (if I make those changes locally catalyst passes its tests).

I'll offer a patch along those lines, but please let me know if there's an alternative approach you'd prefer.

John

**Comment by neilb** [comment]
I think this can be closed.

The breakage was down to people breaking encapsulation – using the fact that `$message->headers` returns an instance of `HTTP::Headers`, which is a blessed hashref, and then using it as a hashref,
rather than calling `$headers->header_field_names` (which filters out the internal `::std_case` key).

Catalyst released [a change](https://metacpan.org/dist/Catalyst-Runtime/changes#L875) which got around this.

The other option would be for `headers()` to return a clone of the headers object which doesn't include `::std_case`, but then that would break the correct handling of that.

**Comment by oalders** [comment]
Thanks @neilb!
